apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB9EMnjCsDLzF3f/weXsdSNnyDy5e+1YYid8dMjxtqsrOKr8oPXxJ28Zt2mjK1QrVV/lQXcG9mxNxvPc90OMRZjEsc9z7IwMRdVZcuz3jYcwgbWwIsFc4U9UlsnajSZJdhNlgYmoOdqQI5YFzkUxTaZrMN0uOM7samhXrn5roVlivqfD1km7uAQyWwWrifBLDLzcgbJPrEi7FjccYqH27YmOT0vGWePce/IdbsC5E029cWGTC7YNfE3IjV69lq5kbjwaUdr5LvpjRhGPFzsVaCVdsNdqxBLSuv44yclq06HvKqjhqCSYO1f1l8yNII4fXVvdE9lhnKkS1sk1rmrdSIPNj/0BMS3VdeczlKF8h015uAxmcSZaJgx+MPhAU0XUxkGR4ezgMSqIinNRdpeF2L2hKwE0lEoGPqPH0MaHpRue1Nm//raISbqQbBTFY7iGeU8x4cFHMjO8tpleyQGpRUlmBGZqbplABoFpEg0ojMupQQhyc/IQ4xdg+zFnGDVyCEeDOz1AVHsDNPbE+YB8u/fc3wDze7tmoJfLTU4NAKMR2O/xrEupi8Ivrn5c44SLjp2NS3n/Jh1gTR1o5PynS8KANnbfHCdEiMVC3c9qwoosGniTyWehJeXMNfNqVnXBdkcO7v6sqlDU4KtC8XQaoRVRSAMAkbdBu7HEI0KIeUNEpa6ROvz3jukQ/LXlyHNSMhycSg/x3UD8uRFwX67GBaJyDYUvN9V85WeTbsg0RaMdDiqdX9nKb8NpQTF7pbdsz2y5WVh79uyOqn7AJbpd0MBnkUBF50a1kTDUBjuOuohsa2WMP0PZx2nHFWaS5LpkSrdY1lravePmkUZTocsivRTXjwx+d4=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

