apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCtzbpM4UrItfFoOQ5UbUJTZHQLjzYRVJP8SOsSqFF/yJ5LtJMrLq+2xmFMpXRfqhDyYJwBHvzwtSbN8yrBNZsgW4Zd1+sQUusBKZrSxa1eSGmjFLDdBt47gHZf5xXA0CJHwMHu5heiIyq+4VjeE9Sk1LWo2jldN/GFGb1tcAX+oQ0gg7bLZvbf/3l54YkN9Ujv3AV2DrA6TJuSTTmFCoqzxsEZSjrZvQSo94/my/PHSfz2v0FDv6MDufeetwiiwB83pvY4n0T246itm0Qq7SE3RI/x0WAzaHG9G2F9ApFbx6qRn/7R45pRoHP08klhmeLQbQ1WOczM8wbuHyyzyPPmIKxpxg1aHJGoMIS8pvObiDPyQxBJraGdWRfAwnu9Cc6dFzEd3dkvLjz3om13zKg0MTnr2dUwaPD6eKfjduyzkugzPb5IXA+RPTN88HgJvvFAbdXNqFn4wBi/0d3feyK/bG/mKQTUCP65r4qMUjtD1FjyhSrQa1jJMU9QDdhLwOMurtyzQLeiNOGRjduKlrdFxp1Qji5q4AJSOzkolkqZyR34w3i5C4PpkMiQVTZBbkeOqPEOjtA+qHrt+uE3Ujx+ZHNMpdpR3/78e9HGXKuV4bCSHmxhBKMAC1OFNBgGvcXDpQn1g6RO2wVWwGknyTvrX7GLdUW/P4mvObA4loONKqFa09QMbX+dLE7Rnvy9bS9potmC41NbB1n+7AoQF4fYhxRG9uFcjJkDA9DAszVoychMtmCid8dTza25b1P4MldroNLrRDrinmAGZJdZGezRNwdFYJpyNCVKYotQFR5QslcveieLu/MSaWteNRHZ8zej3s9x2s6fe6G5zzM6viBF3MvSuKo=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

