---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAajb6vgzgNPIDebcpVg8aKcJT4q4diO30xjbJnpCNT+DNGur7JHGB/VAjnPy7aVDr1O7miFh2MVxjgwN3tefioLiUSqxOkYXhKBPIaDWI6gR6f4sEb46NmOZzGF+0TnLT+DCcu8sw923lsHD5FI/WYniKiXAGuzEleeEmbYUau0e3DKzLRyK2mHkKw28Qg4ZbHg1NLhOGGpl3N855hkQAhELpGgLdtAOorKgaSLlOeex+OVVrRboZ99o+fsxdVLXfkUczYIzqxOKdcMCq5MezvGnxBhu0Qp3uu1fjfDQgVqd5kM1+U3Z6r9eCZ+ZKN+pYgTaEqhjIOSZ+MIVqwWmFUGPGIhhQ2JjOxHgjncNTaldhCaNqcFQciKEy5zadgWBSoF2NKDweJc0pxFZWnqAsiTYoffZRoneGSk00GzdfpyUltKPR2U+/k7n7osaHm5dGzsZsUV9wPgQGgHXI36F/mTSU6XuvwSBY1fU09+LLN8LMahuBeUaF5sSxjGGnxVqoqvbMKra9YYwiNZZHR497AnOX/v7jzMC6Y6AAzhvN1ALM4BSdAFMC492hu/cKX4nWVjMKWNpnMCAsIMdENsqNg52pxZf8b+mkKS3hjNReGV957sReLEvlExUxo1twW8sqmliGrRAvAo0ekK+JesghGIIgwPih+cFnAR2XFnFrgTBDQUXWWBshE4QeFj6fF/7+HG8a8zZhlDnxmr5AVBOfsEGwh9z4b2jlhCb5Gdg+PFn0bDH/Mr9kieOF8DV/bcY9fEDlxHZYDqIuTDMZCqhgKaoMmh7+zV5YydGb85+1T5wXJtlcwOrbh2oNpjHsc+7D8YcHmd/X/XnAYIgnixn4ublPDowM=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system
