apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDFf7jzS664z3I0UTTB+dbB/I4lD+DGBIOiOeCVrHVOUO0viLqivxHZoWxNT9OWnkW0IzZ3qi4DsVyH09johp7us/VFN5qZ0WHWSlKJXijp56UcGR5WPypqDUIyIccz4dm5NxE+qtq4LoR5sS0Zkul8q4ziskh8gGR1L7pOK7xV+WoQae16rIGnfWIBVxhnZytR9gsruNwypi2EIvelICk4/LyshflUagiIH5akgTxrCaGfDfXLd9wQJgx108SG3WtWuaNBDwqElEKKP1oEB4rdV5f0fX90WD2c7YMYREq3H/qTm4x7aEa+H1VsKqjhFn0IOP+KTlskRS0OxoICXE8/GJyW3VBIFfuVGjBUACQdtnXFcT3hWjMEOaQdTAmPo1YH9G5l7YVKOAqVGFmaoX5bO+OHbCnEV02eYgGTLxnl2yinK1rk5UPQ1VZ/Gz0+Mea53dTaTwFsYhzAqztstoEfsHGi5qFqXkHneeoDOFNR+REvYtk2WF+dmCwknVig4k0trLmgxO9N6+1+rtPHcck2UAIRXztxpBdWibItRWdYyg1y5OItlMu9PeStC3zumceBE+5uHLJbqBJloKlkSPILeRGIKyLg6SJqZI4+4054CuI9dmFChOEpY/U9mtMNtnJ1M7Kz/5wgq9vPnMNdsAe4KtrEZuerO4fmPELI91YdmaL8bBYsLCUvZpLqEy8QQ/7b6U+n9YLOgfJWbKP8ixNpDTmLXHDY3vWjA6Iy2WcEV0ToxgH66blUA3jAw3+DEk/no8lFz/+IX1cH0SY4U0nyz5OjJ7WNMVZgxMALKKkB1EoZq79SRYq92TW2tsMs89I0qX+oL/Tr/4wT+FgAjg+JAARNVec=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system