apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBKD3fzHwusU4KCzxusBE0coJZwK6IWIOqVJSKjf5vP6JVsdyz8h2hRydZjAosb6I0sapI0vSo816or8Ug/eX4z8yAVw/8EfTZqdgU8W9ZpxGxT8T8bnu6dH0HXg8yHcmbq1nlweXdcWoBvkebILxrzwQAnpftw9LNeTcFXGmHPxgDRPCoDgOBilADXciJKj2+SYFzULNJJt6m1RW1yXuHSJIcAH6jGKuKPh1WChMgim15Lr9Sftf6vyV44U5+ffcB/lRjWYL6dOdmYBxQM59mB3CjsFAY/1K2rIPwuh5wq+GEgrQ/d6tEePldeRErE/fE9UxFwH96chFK92hLnd7WYKT907rHZVqxtlQP03TpEXQfQZxUVSPVZwrKMBd8gmXOM/57WK7iWZjgpQCRTTCxc/Av6oTHXCINC5UdALG2UZHSc7ODpLfmM9fsslB49cJMyGkPQ+ZN9qnVsfP+e2QCewf3WT2fkQsaSzx/3yJH8NJYNzAMJj0cg7Gl8ZCKmhI0ACA5HEWLJRenUHNu75AKW00Zny6Y3vvKDJUdn/hH6KcDrSioNZATn937xLVqRDe+aR74eVXM16HQWXinLUaAkF2gGaycXcgGOSfxa1kJGgKbKEE6Y7tTdOR9L+LLCahiiVULA1Vo+hiRu09iUUjU4rYGdumn0J0SCeTeqFoIfQ5jdqdh0pxuKgmwMrgG44xzvOw6Je+qVFfSZ+NsxkwA9bzO1RXweGass5vsqptwcyASpDZp1cFkqCdHhNadE3BllMNSrsYsYobXuyVJMN+o1ZeeYUApTZ3EZAGl+wd/S6ozhBSPxpvv+Ibi68NBmHKm0HNlkRT8RXZxFkKj8iXOqoxhdW/s=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

