apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBnBtu3iI3KzV9lZ+Vng/9nNDqGtKGSm63GRDsI1QTO61afOMsHBUGXP6PsFRaIjnoIXetagoUvh2lLcWVg+xI7m6LL/wOm8iEne8KU4g+IyJarqEJWY5xRHg3tPNyuKxOxDooV9X4gFl4xc1LTsRoA9rQ7tFAu1YzBeklq+Pss8xZrt5PQN5K5DAH2gI9xWioa85IhPpOjoY/Wjov1nsOXE25IM/rxDOD0P0QrTVaekQ/j6u5AtUthUsS96MwgmwPyuFTlXlAQ8EM5qGYb/lsyppO957f5zadIwrlKRZivfcO7BXw2x02lmZEn8MVpOvSzsIyOhAIlgGAzzTSnjwUMq+PFzZJslP2wUmfcX6B5UR7nFfgih07rZyURhzIU+CacH7Xn6YjmkbzM74xKv1huSVuX8YinXMennoI1MTJCe2/N73SAv9Z0Pih4S67aJKbLCgPM8c5mH2hJK6DRpfua2iq1o9G9pvCebNZrPpsHwB3eCsWQnEvuS+ABPsoMdr0V/dg437cGJ2Rrqbnfc4K5WOFHEN+qQ9Yc5PBF0en9vosE9imUTgwp446iBv0DqJgTR/lnS6HNpk3Jr7sL/Daq1y4EZqb2KxFulxEY9DxKgQo1ouZ9OFw11F58xK3Q+cDMvEIUH/2c31EOQ/FZ0eAW0ZkZU2aHJYcWkGEnSQAlVCiOdccgvLCuys9jDM9+UZI+bR8vteXECe/rL2JsvAdlQueXZ8Z+3Q7n7602M8KPKkF1oXSA35m6uCcZfscZZMEfZCefyslSW4Y7fbGsXAMrZ0yILMkBDzk9IrMo8hDa05y0FSZjkNBLr3IWx5g4OciTxsxqpXmKXk0hjfJB0tIheGgrvwU=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

