apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgAzF2s/TofwQgdgpbekXILYi5IeQhn8yVG+xaA3E6IWxeiWh4ROHOnVCS5ZzEy0NPOihtsmhxP2eNWIG4qF8a3BnZgHwi+b7NpEULkt2/Z6Q908Se8rL5pR8SX03RhpymZl+VG/vr7SwTKJ24+fqgQxfknjTpJMqxZNXca1lTpR4whxqYAanZ44+cgY2sW47o3+5Aqru9EBjyomIf0q5nQEuwEXPHenJMNMNlMUjQ3RGQ2V7JaFRVliR6URJHFvHHm9Bty6TTouatT3kOI0nItH2jXH9vyFhMRZLNW7aKrIjWsw751Nqd7Dbc0GQ5h6G0sFSXre1QVzZ7pDkwPPp63/6oFWeB2rndnft2hSoia78kv2RpM2CHH8AMt25Wrdj2AAdU8dIQ+GpS6jYJmHwJ0DL5ZYFqRRk/FJcytZD0aMplSg3kZVcauKp9plNa/vG9igtJFDuS0QPQmcD/CphkZ7qt+pLPLM6q+VMOr5K6bP/9cTdBM/r/x78WejqzJVi9skb4zv6YvKUh639/MXpyA9w/fBU+HKQqrGoXnQ6VJIeola6Azg2JVBlUZHKSk18TBYrnW/tD9CPedOrDnNebfCI/ikVfCkllBNlsNkfuI80ITp7hyOXhAYLJ3aIdhbgMoq4U7R+haMMDkvSLiWLYLYMXHHzwcgUT+NsoVBN9W4htsZwE4wT+ExhnOn2cP+m9DOAaf2whIMFWrAFuO7+gM77gDb5HkdC3VOSeGKXpczsKdRYW0aLaOuTYz6oh2ZyAyATt5rEZVLS9y11gKhyhja50/W7d5gJLquX+W+nbSj96b4Zd7n7RB4QWZfVTCNywlvzMr7KTrHe6mBstFTVdbz5s9r5fU=
  template:
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

