kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: cs-api-io
spec:
  routes:
    - conditions:
        - prefix: /
      rateLimitPolicy:
        global:
          descriptors:
            - entries:
                - remoteAddress: {}
      services:
        - name: custom-session-microservice
          port: 80
      loadBalancerPolicy:
        strategy: WeightedLeastRequest
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: cs-api.playexch.io
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*" # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
        - DELETE
      allowHeaders:
        - "*" # allows any origin
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m" # preflight requests can be cached for 10 minutes.