apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/sohelshaikh/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 17 Oct 2023 10:45:22 IST
        provider: minikube.sigs.k8s.io
        version: v1.31.2
      name: cluster_info
    server: https://127.0.0.1:57932
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 17 Oct 2023 10:45:22 IST
        provider: minikube.sigs.k8s.io
        version: v1.31.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/sohelshaikh/.minikube/profiles/minikube/client.crt
    client-key: /Users/sohelshaikh/.minikube/profiles/minikube/client.key
