apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-records
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/sohel-shaikh-wohlig/cross-plane-infra
    path: cloudflare-records
    targetRevision: 1.0.0.3

  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true