apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-alfa-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-alfa-infra
    repoURL: https://github.com/sohel-shaikh-wohlig/cross-plane-infra
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
