apiVersion: batch/v1
kind: Job
metadata:
  name: make-run
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync 
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
      - name: git
        image: alpine/git
        command:
        - git
        - clone 
        - https://github.com/crossplane-contrib/provider-cloudflare.git
        - /provider-repo
        volumeMounts:
        - name:  cloudflare-provider
          mountPath:  /provider-repo
      volumes:
      - name:  cloudflare-provider
        emptyDir: {}
      containers:
        - name: httpie
          image: alpine
          imagePullPolicy: Always
          volumeMounts:
          - name:  cloudflare-provider
            mountPath:  /app
          command: 
          - /bin/sh
          - -c
          - |
            apk install make
            make -v
            apk install go
            cd /app
            date; ls -l /app;
            make run
            sleep 1000
      readinessProbe:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            echo i am after make run
        initialDelaySeconds: 1080
        periodSeconds: 5
            
      restartPolicy: OnFailure
  backoffLimit: 1