apiVersion: batch/v1
kind: Job
metadata:
  name: make-run
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync 
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
      - name: git
        image: alpine/git
        command:
        - git
        - clone 
        - https://github.com/crossplane-contrib/provider-cloudflare.git
        - /provider-repo
        volumeMounts:
        - name:  cloudflare-provider
          mountPath:  /provider-repo
      volumes:
      - name:  cloudflare-provider
        emptyDir: {}
      containers:
        - name: httpie
          image: alpine:3.14
          imagePullPolicy: Always
          volumeMounts:
          - name:  cloudflare-provider
            mountPath:  /app
          command: 
          - /bin/sh
          - -c
          - |
            apt update && apt add install make
            sleep 50;
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                date; ls -l /app;
                cd /app
                make run
            
      restartPolicy: OnFailure
  backoffLimit: 1