apiVersion: batch/v1
kind: Job
metadata:
  name: make-run
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync 
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
      - name: git
        image: alpine/git
        command:
        - git
        - clone 
        - https://github.com/crossplane-contrib/provider-cloudflare.git
        - /provider-repo
        volumeMounts:
        - name:  cloudflare-provider
          mountPath:  /provider-repo
      volumes:
      - name:  cloudflare-provider
        emptyDir: {}
      containers:
        - name: httpie
          image: alpine
          imagePullPolicy: Always
          volumeMounts:
          - name:  cloudflare-provider
            mountPath:  /usr/local/bin/
          command: 
          - /bin/sh
          - -c
          - |
            apk update
            apk add bash
            apk add make
            apk add kubectl
            make -v
            apk add go
            cd /usr/local/bin/
            date; ls -l /usr/local/bin/;
            make run
            sleep 1000
      readinessProbe:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            echo i am after make run
        initialDelaySeconds: 600
        periodSeconds: 5
            
      restartPolicy: OnFailure
  backoffLimit: 1