apiVersion: batch/v1
kind: Job
metadata:
  name: make-run
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync 
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: httpie
          image: alpine:3.14
          imagePullPolicy: Always
          command: 
          - /bin/sh
          - -c
          - data; echo Hello from the JOB run after PostSync of Cloudflare record created
          args:
            [
              
            ]
      restartPolicy: Never
  backoffLimit: 1