apiVersion: batch/v1
kind: Job
metadata:
  name: make-run
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync 
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
      - name: git
        image: alpine/git
        command:
        - git
        - clone 
        - https://github.com/crossplane-contrib/provider-cloudflare.git
        - /provider-repo
        volumeMounts:
        - name:  cloudflare-provider
          mountPath:  /provider-repo
      volumes:
      - name:  cloudflare-provider
        emptyDir: {}
      containers:
        - name: httpie
          image: alpine
          imagePullPolicy: Always
          volumeMounts:
          - name:  cloudflare-provider
            mountPath:  /app
          command: 
          - /bin/sh
          - -c
          - |
            apk update
            apk add bash
            apk add curl

            apk add make
            make -v

            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client
            kubectl cluster-info
            
            apk add go
            cd /app
            date; ls -l /app;
            make run
            sleep 900
      readinessProbe:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            echo i am after make run
        initialDelaySeconds: 600
        periodSeconds: 5
            
      restartPolicy: OnFailure
  backoffLimit: 1
