apiVersion: dns.cloudflare.crossplane.io/v1alpha1
kind: Record
metadata:
  name: cname1
spec:
  forProvider:
    zoneSelector:
      matchLabels:
        identifier: dns-record
    name: cname1
    content: nlb.zodexchange.co.
    proxied: true
    type: CNAME
    zone: 7ea9fe1045447b31a338fbae6a1cfce9

  providerConfigRef:
    name: zodexchange.co