apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: devops-toolkit
spec:
  components:
  - name: backend
    type: backend
    properties:
      image: alpine
      cmd:
      - sleep
      - "1000000"
  - name: frontend
    type: frontend
    properties:
      name: frontend
      image: sohelwohlig/node-js-demo-app
    traits:
    - type: autoscaler
      properties:
        min: 3
    - type: ingress
      properties:
        domain: localhost
        http:
          "/": 80
